window.GALLERY_IMAGES = [
  { "src": "assets/images/gallery/pool-balcony.jpg", "alt": "Pool view from guest balcony", "width": 900, "height": 1600 },
  { "src": "assets/images/gallery/lobby-staircase.jpg", "alt": "Hotel lobby and staircase", "width": 900, "height": 1600 },
  { "src": "assets/images/gallery/luggage-cart.jpg", "alt": "Lobby luggage cart", "width": 900, "height": 1600 },
  { "src": "assets/images/gallery/room-entry.jpg", "alt": "Modern guest room entrance", "width": 900, "height": 1600 },
  { "src": "assets/images/gallery/keyless-entry.jpg", "alt": "Key card room access", "width": 900, "height": 1600 },
  { "src": "assets/images/gallery/corridor-hexagon.jpg", "alt": "Hotel corridor with hexagon wall art", "width": 900, "height": 1600 },
  { "src": "assets/images/gallery/shower-detail.jpg", "alt": "Marble bathroom shower", "width": 900, "height": 1600 },
  { "src": "assets/images/gallery/bathroom-vanity.jpg", "alt": "Guest bathroom vanity", "width": 900, "height": 1600 },
  { "src": "assets/images/gallery/corridor-gold-carpet.jpg", "alt": "Hotel hallway", "width": 900, "height": 1600 },
  { "src": "assets/images/gallery/level-directory.jpg", "alt": "Level 6 directory sign", "width": 1086, "height": 1448 },
  { "src": "assets/images/gallery/elevator-level-6.jpg", "alt": "Elevator to hotel level", "width": 1086, "height": 1448 },
  { "src": "assets/images/gallery/pool-deck-alt.jpg", "alt": "Outdoor swimming pool deck", "width": 897, "height": 1600 },
  { "src": "assets/images/gallery/king-room-wide.jpg", "alt": "King bedroom with honeycomb lighting", "width": 1600, "height": 1050 },
  { "src": "assets/images/gallery/bed-detail-1.jpg", "alt": "Guest room bed detail", "width": 938, "height": 1600 },
  { "src": "assets/images/gallery/bed-detail-2.jpg", "alt": "Guest room accent wall", "width": 930, "height": 1600 },
  { "src": "assets/images/gallery/twin-beds.jpg", "alt": "Twin room beds", "width": 1280, "height": 576 },
  { "src": "assets/images/gallery/suite-living-alt.jpg", "alt": "Suite living area", "width": 1448, "height": 1086 },
  { "src": "assets/images/gallery/suite-room-wide.jpg", "alt": "Twin room with seating area", "width": 1448, "height": 1086 },
  { "src": "assets/images/gallery/atrium-windows.jpg", "alt": "Hotel atrium and windows", "width": 900, "height": 1600 },
  { "src": "assets/images/gallery/suite-bath-wide.jpg", "alt": "Suite bathroom with bathtub", "width": 1600, "height": 900 },
  { "src": "assets/images/gallery/bath-shower-suite.jpg", "alt": "Suite shower and bath", "width": 900, "height": 1600 },
  { "src": "assets/images/gallery/bath-shower-alt.jpg", "alt": "Modern suite bathroom", "width": 1600, "height": 900 },
  { "src": "assets/images/gallery/lobby-lounge-wide.jpg", "alt": "Lobby lounge seating", "width": 1574, "height": 708 },
  { "src": "assets/images/gallery/lobby-seating.jpg", "alt": "Lobby seating area", "width": 1600, "height": 720 }
];
